name: First Workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello
        run: echo "Hello!"
      - name: Print goodbye
        run : echo "Bye bye!"
      - name: Test pipe operator
        run : |
              echo "First respose"
              echo "Second response"
      - name: Use reusable workflow
        uses: ./.github/workflows/reusable.yml