name: Deploy project
on: push
jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6
      - name: Install dependecy
        working-directory: ./02 Starting Project
        run: npm ci #uses exact same versions as in package-lock.json
      - name: Run tests
        working-directory: ./02 Starting Project
        run: npm test
  deploy_job:
    needs: test_job
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6
      - name: Install dependecy
        working-directory: ./02 Starting Project
        run: npm ci
      - name: Build project
        working-directory: ./02 Starting Project
        run: npm run build
      - name: Deploy
        run: echo "Deploying to server..."